services:
  devenv:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SSH_PORT: 2222
        DEV_USER: devuser
    init: true
    # Ubuntu environment will map host port 2222 to container port 2222
    ports:
      - "2222:2222"
    volumes:
      - /var/lib/docker/rootless-data/workspace:/home/devuser/workspace:rw
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    restart: unless-stopped
    networks:
      - devenv_network
    healthcheck:
      test: ["CMD-SHELL", "sshd -T > /dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    mem_limit: 4g
    cpus: "2.0"

networks:
  devenv_network:
    driver: bridge
